version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: "finance_db"
    environment:
      - POSTGRES_DB=financedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
